name: model-fashion-mnist
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python model.py
          
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Model Performance" >> report.md
          cml-publish accuracy.png --md >> report.md
          cml-publish loss.png --md >> report.md
          
          cml-send-comment report.md
